# Generated by Django 4.2 on 2024-11-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower_alter_bookinstance_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Введите наименование издательства', max_length=20, verbose_name='Издательство')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, help_text='Введите сведения об авторе', null=True, verbose_name='Сведения об авторе'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Введите фото автора', null=True, upload_to='images', verbose_name='Фото автора'),
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='Нет фотографий обложки', help_text='Введите изображение обложки', upload_to='images', verbose_name='Изображение обложки'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену книги', max_digits=7, null=True, verbose_name='Цена (руб.)'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, help_text='Введите год издания', max_length=4, null=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автора (авторов) книги', to='catalog.author', verbose_name='Автор (авторы) книги'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Выберите издательство', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.publisher', verbose_name='Издательство'),
        ),
    ]
